In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt

In [2]:
finalDf = pd.read_csv('final_dataset.csv')

In [23]:
finalDf = pd.read_csv('final_dataset.csv')

genreSet = set()
genreList = list(genreSet)
genreDict = {}

for index, row in finalDf.iterrows():
    genreList = row.listed_in.split(', ')
    for genre in genreList:
        genreSet.add(genre)

for genre in genreSet:
    genreList.append(genre)
    genreDict[genre] = [0,0]
    
for genre in genreList:
    for index, row in finalDf.iterrows():
        if genre in row.listed_in:
            genreDict[genre][0] += 1
            genreDict[genre][1] += row.user_rating

{'Reality TV': [2, 130.0], 'TV Comedies': [42, 3538.0], 'TV Sci-Fi & Fantasy': [2, 175.0], 'Crime TV Shows': [14, 1274.0], 'TV Action & Adventure': [3, 243.0], 'TV Thrillers': [2, 185.66666666666669], 'International TV Shows': [6, 473.0], 'Anime Series': [2, 145.0], 'TV Mysteries': [4, 381.0], 'Classic & Cult TV': [2, 196.0], 'Romantic TV Shows': [4, 365.0], 'Teen TV Shows': [5, 384.0], 'TV Horror': [2, 139.0], 'Docuseries': [1, 88.0], 'Science & Nature TV': [1, 88.0], 'Stand-Up Comedy & Talk Shows': [1, 94.0], 'TV Dramas': [31, 2658.0], 'Spanish-Language TV Shows': [1, 67.0], "Kids' TV": [13, 984.6666666666667], 'British TV Shows': [2, 188.0]}

In [28]:
# Create a dataframe with MPAA Ratings as rows.
genre_df = pd.DataFrame({'genre':genreList})
genre_final_df = pd.DataFrame(columns = ['Genre', 'User_Rating'])
# final_df = final_df.append(pd.Series(currRow, index=final_df.columns), ignore_index=True)
    
for genre in genreList:
    currRow = [genre, genreDict[genre][1]/genreDict[genre][0]]
    genre_final_df = genre_final_df.append(pd.Series(currRow, index=genre_final_df.columns), ignore_index=True)

genre_final_df

                           Genre  User_Rating
0              Classic & Cult TV    98.000000
1                    TV Comedies    84.238095
2                     Reality TV    65.000000
3                    TV Comedies    84.238095
4            TV Sci-Fi & Fantasy    87.500000
5                 Crime TV Shows    91.000000
6          TV Action & Adventure    81.000000
7                   TV Thrillers    92.833333
8         International TV Shows    78.833333
9                   Anime Series    72.500000
10                  TV Mysteries    95.250000
11             Classic & Cult TV    98.000000
12             Romantic TV Shows    91.250000
13                 Teen TV Shows    76.800000
14                     TV Horror    69.500000
15                    Docuseries    88.000000
16           Science & Nature TV    88.000000
17  Stand-Up Comedy & Talk Shows    94.000000
18                     TV Dramas    85.741935
19     Spanish-Language TV Shows    67.000000
20                      Kids' TV    75.743590
21              British TV Shows    94.000000